### ISSUE TITLE
Import Bookmarks Experiment Messages

### ISSUE THREAD

**Issue by lmegviar** [mozilla-l10n/nimbus-l10n#1]
### Information about the experiment

[This experiment ](https://docs.google.com/document/d/1NRthOCpXLpMLx90mTTWolRs5NXYG8OCSlFDtz_58-mo/edit?usp=sharing)will use the same strings across all treatments, with variations in the image used.

### List of locales

fr, de, en

### Deadline

2023-01-10

### Content to translate
[ImportBookmarksExperiment.txt](https://github.com/mozilla-l10n/nimbus-l10n/files/10228518/ImportBookmarksExperiment.txt) (.ftl type not supported for upload)

```
## Strings for messages to be used in experiments encouraging users to import their bookmarks

import-bookmarks-experiment-title = Bring along what matters

import-bookmarks-experiment-subtitle = Start fresh without starting from scratch, import your passwords, bookmarks, and more to make Firefox feel a little bit like home.

# Modal dialog primary button to import bookmarks
import-bookmarks-experiment-primary-button-label = Import to Firefox

# Modal secondary action link to close modal dialog
import-bookmarks-experiment-secondary-button-label = Not now
```

**Comment by flodolo** [comment]
Project is fully localized, you can find the translation in the JSON linked above.
