### ISSUE TITLE
[NEW]: NP Survey: New vs. Existing vs. Returning (DE, es-ES, FR, IT, RU, zh-CN)

### ISSUE THREAD

**Issue by nuggetsnegin** [mozilla-l10n/nimbus-l10n#24]
### Information about the experiment

[Experimenter](https://experimenter.services.mozilla.com/nimbus/new-profile-survey-new-vs-existing-vs-returning-all-locales-fx123/summary)
[Experiment Brief](https://docs.google.com/document/d/1oS-a2mQDUPMGUTitqbg61tDhvew1OwgEwziTDxMH8u4/edit#heading=h.9lxcxot720r1)
[Figma](https://www.figma.com/file/EOMlYBMJ8cHBnHEteInddF/NUO-Experiments-2024?type=design&node-id=49-10561&mode=design&t=M5tMXnAohR3DszIH-0)

We had a last minute request from legal to include a "Privacy Notice" link in our localized new profile survey. We've changed the scope of the survey to include the following locales (instead of all):
`'de', 'es-ES', 'fr', 'it', 'ru', 'zh-CN'`

The privacy notice link, will link to https://www.mozilla.org/privacy/websites/ and it will be in both the treatment-a and treatment-b branch:
```
          "label": {
            "raw": {
              "$l10n": {
                "id": "new-profile-survey-privacy-notice-link-label",
                "text": "Privacy Notice",
                "comment": ""
              }
            }
```

Hopefully this should be a simple translation, we noticed that newtab.ftl has a string id for `Privacy Notice` but unfortunately it will require on-train changes to support and we want to run this experiment in FX123. We're hoping to launch this experiment on Feb 28th but we need QA to do a spot check on this so I set the deadline to be a bit earlier but let me know if the date cannot be accommodated!

### Deadline

2024-02-16

**Comment by flodolo** [comment]
We only support a limited set of locales through this workflow (de, fr, it). Also, the expectations is that new experiments use the [new system](https://experimenter.info/localization-process/#multi-locale-recipe-firefox-113-and-later) (one recipe for all locales with message references).

With that said, if you only need the translation of Privacy Notice, and it's copied and pasted in the recipe, you can use the translations from here: https://transvision.flod.org/string/?entity=browser/browser/preferences/preferences.ftl:collection-privacy-notice&repo=gecko_strings

**Comment by nuggetsnegin** [comment]
> We only support a limited set of locales through this workflow (de, fr, it). Also, the expectations is that new experiments use the [new system](https://experimenter.info/localization-process/#multi-locale-recipe-firefox-113-and-later) (one recipe for all locales with message references).
> 
> With that said, if you only need the translation of Privacy Notice, and it's copied and pasted in the recipe, you can use the translations from here: https://transvision.flod.org/string/?entity=browser/browser/preferences/preferences.ftl:collection-privacy-notice&repo=gecko_strings

Ah, my mistake for both the limited locales and multi experiment request (that was unintentional 😓). Looks like the link you provided fits my use case so I think it's safe to close this request!
