### ISSUE TITLE
Ask Windows & Mac Desktop Early Day Profiles about their Firefox Use Case

### ISSUE THREAD

**Issue by nuggetsnegin** [mozilla-l10n/nimbus-l10n#27]
### Information about the experiment

Running a microsurvey asking new profile users about their Firefox usage (`work`, `personal`, `school`, or `other`). Localization request is for the survey title, survey options, and primary button and link.
* [Experiment recipe](https://experimenter.services.mozilla.com/nimbus/ask-windows-mac-desktop-early-day-profiles-about-their-firefox-use-case/summary)
* Locales: EN-*, FR, IT, DE
* [Experiment brief](https://docs.google.com/document/d/1tbpH0E-HvFcQIMar25mNTgxYARjJDAUY9BlTq6Lj-Wg/edit)

`thanks-toast-title` localization was repurposed from [new tab micro survey experiment](https://experimenter.services.mozilla.com/nimbus/new-tab-microsurvey-relevance-satisfaction-new-users-others/summary) but let me know if I should remove that!

**Comment by flodolo** [comment]
> _No response_

What is the current timeline for the experiment?

**Comment by mozilla-pontoon** [comment]
Created pull request: https://github.com/mozilla-l10n/nimbus-l10n/pull/28

**Comment by flodolo** [comment]
> `thanks-toast-title` localization was repurposed from [new tab micro survey experiment](https://experimenter.services.mozilla.com/nimbus/new-tab-microsurvey-relevance-satisfaction-new-users-others/summary) but let me know if I should remove that!

You don't really need to fill the Localization Substitutions section. The whole JSON will be provided here once translations are completed.

**Comment by nuggetsnegin** [comment]
> > _No response_
> 
> What is the current timeline for the experiment?

May 14th is when we'd like to launch, so having the experiment ready by end of next week would be ideal to get it into QA but it's not a hard timeline.

**Comment by mozilla-pontoon** [comment]
Translation has been completed for `ask_windows_mac_desktop_early_day_profiles_about_their_firefox_use_case_2024.ftl`.

Here’s the data to copy in the Localization field in Experimenter:

```
{
  "de": {
    "privacy-notice-label": "Datenschutzhinweis",
    "submit-button-label": "Absenden",
    "survey-checkbox-other-label": "Sonstiges",
    "survey-checkbox-personal-label": "Persönliches",
    "survey-checkbox-school-label": "Schule",
    "survey-checkbox-work-label": "Arbeit",
    "survey-title": "Wozu verwenden Sie Firefox?",
    "thanks-toast-title": "Danke für Ihre Rückmeldung!"
  },
  "en-CA": {
    "privacy-notice-label": "Privacy Notice",
    "submit-button-label": "Submit",
    "survey-checkbox-other-label": "Other",
    "survey-checkbox-personal-label": "Personal",
    "survey-checkbox-school-label": "School",
    "survey-checkbox-work-label": "Work",
    "survey-title": "What do you use Firefox for?",
    "thanks-toast-title": "Thanks for your feedback!"
  },
  "en-GB": {
    "privacy-notice-label": "Privacy Notice",
    "submit-button-label": "Submit",
    "survey-checkbox-other-label": "Other",
    "survey-checkbox-personal-label": "Personal",
    "survey-checkbox-school-label": "School",
    "survey-checkbox-work-label": "Work",
    "survey-title": "What do you use Firefox for?",
    "thanks-toast-title": "Thanks for your feedback!"
  },
  "en-US": {
    "privacy-notice-label": "Privacy Notice",
    "submit-button-label": "Submit",
    "survey-checkbox-other-label": "Other",
    "survey-checkbox-personal-label": "Personal",
    "survey-checkbox-school-label": "School",
    "survey-checkbox-work-label": "Work",
    "survey-title": "What do you use Firefox for?",
    "thanks-toast-title": "Thanks for your feedback!"
  },
  "fr": {
    "privacy-notice-label": "Politique de confidentialité",
    "submit-button-label": "Envoyer",
    "survey-checkbox-other-label": "Autre",
    "survey-checkbox-personal-label": "Personnel",
    "survey-checkbox-school-label": "École",
    "survey-checkbox-work-label": "Travail",
    "survey-title": "À quoi vous sert Firefox ?",
    "thanks-toast-title": "Merci de votre retour !"
  },
  "it": {
    "privacy-notice-label": "Informativa sulla privacy",
    "submit-button-label": "Invia",
    "survey-checkbox-other-label": "Altro",
    "survey-checkbox-personal-label": "A scopo personale",
    "survey-checkbox-school-label": "Scuola",
    "survey-checkbox-work-label": "Lavoro",
    "survey-title": "Per cosa utilizzi Firefox?",
    "thanks-toast-title": "Grazie per aver condiviso la tua opinione."
  }
}
```

**Comment by nuggetsnegin** [comment]
Wow, that was so fast! Thanks @flodolo :)
