### ISSUE TITLE
Translate Pin to Taskbar/Set to Default Fox Doodle Winners

### ISSUE THREAD

**Issue by aminomancer** [mozilla-l10n/nimbus-l10n#3]
### Information about the experiment

[Experiment brief](https://docs.google.com/document/d/1PH0lgpELMamV2xEd9g_aMTDk7SBPX2w_f4yMmh6Zcpo/edit#heading=h.cdqujm395s3r). All branches have the same copy.

### List of locales

- fr
- de
- en

### Content to translate

```
## Strings for messages to be used in experiments encouraging users to set
## Firefox to default or pin Firefox to taskbar.

pin-default-peace-of-mind-headline = We’ve got you covered
pin-default-peace-of-mind-body = Every month, Firefox blocks an average of 3,000+ trackers per user, giving you safe, speedy access to the good internet.

pin-default-better-internet-headline = A better internet starts with you
pin-default-better-internet-body = When you use Firefox, you’re voting for an open and accessible internet that’s better for everyone.

pin-default-welcome-back-headline = Welcome back
pin-default-welcome-back-body = Here’s a quick reminder that you can keep your favorite indie browser just one click away.

pin-default-secondary-button-label = Not now
```

For context, the primary buttons will use strings from m-c that say `Pin Firefox to taskbar` or `Open my links with Firefox`.

**Comment by flodolo** [comment]
Thanks, request looks good.

> For context, the primary buttons will use strings from m-c that say `Pin Firefox to taskbar` or `Open my links with Firefox`.

Do you mind if I add them to the request? I also plan to import the existing translations to speed things up.

**Comment by aminomancer** [comment]
> Do you mind if I add them to the request? I also plan to import the existing translations to speed things up.

The problem I ran into is that the primary CTA labels are [platform-dependent](https://searchfox.org/mozilla-central/rev/e66cff951667dacd0faa95dfde830564a58a8a3f/browser/locales/en-US/browser/newtab/onboarding.ftl#232-235). And we don't have any way to implement a platform switch in Experimenter. So that particular one must be a Fluent string. Whereas for the other ones, it was requested that we use raw strings in Experimenter, with a different version of the experiment for each locale.

So as far as I can tell, if we added new translations for the primary CTA labels, they would need to land in m-c. But that can't work, as the experiment targets Fx 106 users and up.

**Comment by flodolo** [comment]
Thanks, that makes sense. I'll try to work on it first time tomorrow.

**Comment by flodolo** [comment]
One nit: the Figma file had some localization that should have been ported over (took care of that).

Files are out for translations, I'll ping here when they're done (I put next Monday as deadline, hopefully they'll make it earlier than that).

**Comment by aminomancer** [comment]
> One nit: the Figma file had some localization that should have been ported over (took care of that).
> 
> Files are out for translations, I'll ping here when they're done (I put next Monday as deadline, hopefully they'll make it earlier than that).

Thanks for catching that!

**Comment by aminomancer** [comment]
Hey @flodolo I missed a string that is used in one of the experiments. This one is not platform-dependent:
```
# Primary action label for the Set to Default message
pin-default-set-default-primary-button-label = Open my links with Firefox
```
Sorry about that 😓

**Comment by flodolo** [comment]
Added, luckily we had this one already translated.

**Comment by flodolo** [comment]
Translations are available here
https://github.com/mozilla-l10n/nimbus-l10n/blob/main/.github/storage/pin_taskbar_fox_doodle_2023.json

Look out for non-breaking spaces in French:
* GitHub doesn't show them
* Firefox looses them when doing copy and paste

If you download the [raw file](https://raw.githubusercontent.com/mozilla-l10n/nimbus-l10n/main/.github/storage/pin_taskbar_fox_doodle_2023.json) and open it in Visual Studio Code, you should see them clearly.

<img width="742" alt="Screenshot 2023-02-09 alle 11 22 39" src="https://user-images.githubusercontent.com/3644868/217786415-eed96fc9-86d3-43e6-b81f-1b2ffd0a3026.png">
