### ISSUE TITLE
Firefox VPN Spotlight modal test content

### ISSUE THREAD

**Issue by chrisrooneys** [mozilla-l10n/nimbus-l10n#5]
### Information about the experiment

We are running a/b tests on a VPN spotlight modal in Firefox. Here's a link to the project info: [Google doc](https://docs.google.com/document/d/1NFnevTfUU715nMVs_l9AzYcP6UEpIaU9cDyJXgMjhiM/edit?usp=sharing)

There are two versions of content, identical except for the inclusion of a promotional code in one of them. Where the tests also differ is in the imagery used, which you can see in the Figma file linked in this ticket.

### List of locales

Locale: EN, DE, FR, ITL

### Content to translate

Here is a Figma file showing how this content will be displayed: [Figma](https://www.figma.com/file/RZEKnh2JxofSb5kUmtl7CM/VPN-Spotlight-Modal?type=design&node-id=120%3A1250&t=1MCwY7QJLW2N9061-1)

**Comment by flodolo** [comment]
@chrisrooneys 

For the future, you can see an example of request here: https://github.com/mozilla-l10n/nimbus-l10n/issues/3

Asking me to copy and paste content from a Google Doc increases the risk of making mistakes, because there is nobody reviewing my work (i.e. comparing the request with the doc).

**Comment by chrisrooneys** [comment]
@flodolo Will do. The instructions suggested linking to the content as one of the options. I'm happy to copy/paste here, just give me a second!

**Comment by flodolo** [comment]
Resolved confusion in Zoom. This is the pull request setting up the experiment
https://github.com/mozilla-l10n/nimbus-l10n/pull/6

**Comment by flodolo** [comment]
All locales are already translated, but I would wait until Monday just in case they change their mind on a translation (I did put May 17 as deadline)
https://github.com/mozilla-l10n/nimbus-l10n/blob/main/.github/storage/vpn_spotlight_modal_2023.json

**Comment by flodolo** [comment]
Translation has been completed. 

As described in the [documentation](https://experimenter.info/localization-process/#retrieve-translated-content), someone will need to copy and paste the translation from [here](https://github.com/mozilla-l10n/nimbus-l10n/blob/main/.github/storage/vpn_spotlight_modal_2023.json) into the Experimenter UI.
