### ISSUE TITLE
Desktop-to-Mobile Experiment: Signed into Account/Promote Sync with Mobile

### ISSUE THREAD

**Issue by sarahhjchung** [mozilla-l10n/nimbus-l10n#50]
### Information about the experiment

**Links**

- [Recipe in Experimenter](https://experimenter.services.mozilla.com/nimbus/desktop-feature-callout-signed-into-account/summary)
- [Experiment brief](https://docs.google.com/document/d/1bTRtgeuuTXdsYbeWRzbxkm8XLsA8T0LPwrDhvSpJwOw/edit?tab=t.0#heading=h.uoblsnu302hk)
- [Figma - final designs](https://www.figma.com/design/MsU0bn3O6tXj2GxOeJ8bML/Desktop-to-mobile-onboarding-(QR-codes%2C-etc)?node-id=1300-5530&node-type=frame&m=dev)

**List of Locales**

en-US, en-CA, en-GB, FR and DE

**Background**

This messaging experiment targets existing Mozilla Accounts users who do not have a synced mobile device and presents them with contextual messaging promoting the benefit of downloading Firefox for mobile and syncing desktop and mobile devices. All variants get users into the [login funnel flow](https://miro.com/app/board/uXjVMqa4bNo=/) to complete their download and sync. We do not know if users already have Firefox for mobile downloaded so the content is written to work around that issue. We are testing 2 variants:

- Treatments A & B offer a QR code to scan and download Firefox for mobile.
    - Once users download FF for mobile, the login funnel flow will take them through the steps to sync. 
    - If users already have FF for mobile, they can click on the Sync to Mobile button instead. They will be taken to the sync screen in the login funnel flow and get a different QR code to scan and sync devices.

### Deadline

2024-11-12

**Comment by flodolo** [comment]
> 2024-11-08

Pointing out that the deadline is not realistic (this is going through community). 
I will set up the project tomorrow, but it will likely take 3–4 days to be completed (early next week).

**Comment by mozilla-pontoon** [comment]
Created pull request: https://github.com/mozilla-l10n/nimbus-l10n/pull/51

**Comment by mozilla-pontoon** [comment]
Translation has been completed for `desktop_feature_callout_signed_into_account_2024.ftl`.

Here’s the data to copy in the Localization field in Experimenter:

```
{
  "de": {
    "desktop-to-mobile-headline": "Herunterladen, synchronisieren und loslegen!",
    "desktop-to-mobile-subtitle": "Scanne den QR-Code, um Firefox fürs Handy herunterzuladen. Wähle nach der Installation „Mit Handy synchronisieren“, um unterwegs auf Passwörter, Lesezeichen und mehr zuzugreifen.",
    "dismiss-button-label": "Schließen",
    "sync-to-mobile-button-label": "Mit Handy synchronisieren"
  },
  "en-CA": {
    "desktop-to-mobile-headline": "Download, sync, and go!",
    "desktop-to-mobile-subtitle": "Scan the QR code to download Firefox for mobile. Once installed, select “Sync to mobile” to access your passwords, bookmarks, and more on the go.",
    "dismiss-button-label": "Dismiss",
    "sync-to-mobile-button-label": "Sync to mobile"
  },
  "en-GB": {
    "desktop-to-mobile-headline": "Download, sync, and go!",
    "desktop-to-mobile-subtitle": "Scan the QR code to download Firefox for mobile. Once installed, select “Sync to mobile” to access your passwords, bookmarks, and more on the go.",
    "dismiss-button-label": "Dismiss",
    "sync-to-mobile-button-label": "Sync to mobile"
  },
  "en-US": {
    "desktop-to-mobile-headline": "Download, sync, and go!",
    "desktop-to-mobile-subtitle": "Scan the QR code to download Firefox for mobile. Once installed, select “Sync to mobile” to access your passwords, bookmarks, and more on the go.",
    "dismiss-button-label": "Dismiss",
    "sync-to-mobile-button-label": "Sync to mobile"
  },
  "fr": {
    "desktop-to-mobile-headline": "Téléchargez, synchronisez et c’est parti !",
    "desktop-to-mobile-subtitle": "Scannez le code QR pour télécharger Firefox pour mobile. Une fois l’installation terminée, sélectionnez « Synchroniser avec votre appareil mobile » pour accéder à vos mots de passe, marque-pages et bien plus encore lors de vos déplacements.",
    "dismiss-button-label": "Ignorer",
    "sync-to-mobile-button-label": "Synchroniser avec votre appareil mobile"
  }
}
```
