### ISSUE TITLE
Add an account login card to new profile onboarding (about:welcome rollout for select locales)

### ISSUE THREAD

**Issue by lmegviar** [mozilla-l10n/nimbus-l10n#52]
### Information about the experiment

[Experimenter Link](https://experimenter.services.mozilla.com/nimbus/rollout-npo-account-login-screen-windows-select-locales/summary)

**Locales:** 
- French
- German
- Italian
- Russian
- Spanish (Argentina)
- Spanish (Chile)
- Spanish (Mexico)

[Brief for original experiment](https://docs.google.com/document/d/1rA6QCA0mou0BvxktkXJZp6aeilNWG-i6pa_FpO5EKMY/edit?tab=t.0#heading=h.fcmkt8fg0znd)

Note we only need translations for the strings in the final card, "AW_ACCOUNT_LOGIN" (the `"AW_AMO_INTRODUCE"` screen targets EN-* only):

`    {
      "id": "AW_ACCOUNT_LOGIN",
      "targeting": "!isFxASignedIn",
      "content": {
        "fullscreen": true,
        "position": "split",
        "split_narrow_bkg_position": "-228px",
        "image_alt_text": {
          "string_id": "mr2022-onboarding-gratitude-image-alt"
        },
        "background": "url('https://firefox-settings-attachments.cdn.mozilla.net/main-workspace/ms-images/6d15f99b-4ba8-49ba-b039-071d58fd4d2f.svg') var(--mr-secondary-position) no-repeat var(--mr-screen-background-color)",
        "progress_bar": true,
        "logo": {},
        "title": {
          "raw": "Sync your data across devices"
        },
        "subtitle": {
          "raw": "Sign up for an account and all of your important info — passwords, bookmarks, and more — will be securely stored and available when you sign in to any device."
        },
        "secondary_button": {
          "label": {
            "string_id": "mr2-onboarding-start-browsing-button-label"
          },
          "style": "secondary",
          "action": {
            "navigate": true
          }
        },
        "primary_button": {
          "label": {
            "raw": "Sign up or sign in"
          },
          "action": {
            "data": {
              "entrypoint": "newuser-onboarding-desktop"
            },
            "type": "FXA_SIGNIN_FLOW",
            "navigate": true
          }
        }
      }
    }`

### Deadline

2024-11-08

**Comment by flodolo** [comment]
Sorry, I need to push back on this request. From the Experimenter [documentation](https://experimenter.info/localization-process/#multi-locale-recipe-firefox-113-and-later):

> Unless there is pre-established availability from staff to localize the content, expect about 7 days to complete the process from request to delivery. 

It's Nov 6 here, the requested deadline is Nov 8. This work goes through community, and there are two other experiments happening. Both the team and volunteers' bandwidth are limited.

> Given the short turn-around for localization, we are currently limiting the requests to tier 1 locales (de, fr) — where we potentially also have internal copywriters as a backup — and locales that have internal staff available for support (it, ja).

We only support German, French, and Italian through this pipeline.  Spanish (all variants) and Russian are not supported.

> Note we only need translations for the strings in the final card, "AW_ACCOUNT_LOGIN" (the "AW_AMO_INTRODUCE" screen targets EN-* only)

That requires manual steps, as the automation will extract the entire experiment. Also, the experiment is not set up correctly for extraction (content is hard-coded).

Options to move forward:
* Only do de, fr, it and adjust the deadline, noting that this still requires manual work to set it up and my team will have limited availability next week.
* Do all locales and go through a different pipeline (paid translation). The content to be localized needs to be manually extracted into a spreadsheet and then put back into the system. Given it's 3 strings, it will incur a minimum rate. See this [Confluence page](https://mozilla-hub.atlassian.net/wiki/spaces/FDPDT/pages/183861372/Localization+Intake+Process#LSP-Service-Requests) on how to do a request.
* Hack it and accept the limitations (we can machine translate these strings using trained Google engines for the requested locales).

**Comment by flodolo** [comment]
```
en-US
Sync your data across devices
Sign up for an account and all of your important info — passwords, bookmarks, and more — will be securely stored and available when you sign in to any device.
Sign up or sign in

it
Sincronizza i tuoi dati su tutti i dispositivi
Crea un account e tutte le tue informazioni più importanti (password, segnalibri e altro ancora) saranno archiviate in modo sicuro e disponibili quando accedi da qualsiasi dispositivo.
Registrati o accedi

de
Synchronisiere deine Daten zwischen Geräten
Melde dich für ein Konto an und all deine wichtigen Infos – Passwörter, Lesezeichen und mehr – werden sicher gespeichert und sind verfügbar, wenn du dich auf irgendeinem Gerät anmeldest.
Anmelden oder registrieren

fr
Synchronisez vos données entre vos appareils
Créez un compte et toutes vos informations importantes (mots de passe, marque-pages, et plus encore) seront stockées en toute sécurité et disponibles lorsque vous vous connecterez sur n’importe quel appareil.
S’inscrire ou se connecter

es-*
Sincroniza tus datos entre dispositivos
Regístrate para obtener una cuenta y toda tu información importante (contraseñas, marcadores y más) se guardará de forma segura y estará disponible cuando inicies sesión en cualquier dispositivo.
Regístrate o inicia sesión

ru
Синхронизируйте свои данные на всех устройствах
Зарегистрируйте аккаунт, и вся ваша важная информация — пароли, закладки и многое другое — будет надежно храниться и доступна после входа в систему на любом устройстве.
Зарегистрироваться или войти
```

**Comment by flodolo** [comment]
Closing this, let us know if you need anything else.
