### ISSUE TITLE
[NEW]: (Translate strings for Device Migration Experiment)

### ISSUE THREAD

**Issue by halemu** [mozilla-l10n/nimbus-l10n#9]
### Information about the experiment

[Experiment Brief](https://docs.google.com/document/d/1QA93jVD_wUXnKUhLXjQ64Td8AUOUS1RGrLdgyKDeFXs/edit)

This will be to translate the strings used in the Spotlight modal.
![image](https://github.com/mozilla-l10n/nimbus-l10n/assets/123992137/575f2130-6da6-45dd-9bb7-c8eba87abcb6)

### List of locales

* English (en)
* German (de), 
* French (fr), 
* Italian (it)

### Content to translate

```
device-migration-fxa-spotlight-header = Using an older device?
device-migration-fxa-spotlight-body = Back up your data to make sure you don’t lose important info like bookmarks and passwords –– especially if you switch to a new device.
device-migration-fxa-spotlight-primary-button = How to back up my data
device-migration-fxa-spotlight-link = Remind me later
```

**Comment by aminomancer** [comment]
We need strings translated for both versions 1 and 2. flod, since these are 2 branches for 1 experiment, is it better if we do both in this issue, or file 2 separate issues? Thanks.

**Comment by flodolo** [comment]
One issue. 

Today we already had 3 issues filed for experiments in a few hours, and that created unnecessary churn for both German and French.

**Comment by aminomancer** [comment]
@halemu the final strings are in the [copy doc](https://docs.google.com/document/d/11kNl7JEIlkf3ZUpg5jmOTEm4GZQCzXFODB_4FHHiVMM/edit), let's use those please since I haven't recently confirmed the brief is up to date

**Comment by flodolo** [comment]
Clarified on Slack, file has been set up in https://github.com/mozilla-l10n/nimbus-l10n/pull/10 and exposed for localization

**Comment by flodolo** [comment]
Translations will be available [here](https://github.com/mozilla-l10n/nimbus-l10n/blob/main/.github/storage/device_migration_2023.json) as soon as locales are complete.

**Comment by flodolo** [comment]
Translation has been completed. 

As described in the [documentation](https://experimenter.info/localization-process/#retrieve-translated-content), someone will need to copy and paste the translation from [here](https://github.com/mozilla-l10n/nimbus-l10n/blob/main/.github/storage/device_migration_2023.json) into the Experimenter UI.
